services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm start

  db:
    image: nouchka/sqlite3
    volumes:
      - db-data:/data

volumes:
  db-data:
